version: "3.8"

services: 
    app:
        build: .
        container_name: luminaria_app
        command: quasar dev -m pwa &
        ports:
            - "3003:3003"
        volumes: 
            - .:/usr/app  
                
              