name: Deploy
on:
  push:
    branches:
      - 'master'      
jobs: 
  deploy:
    name: Quasar Publish
    runs-on: ubuntu-20.04
    container: node:12.16.2
    steps:
      - uses: actions/checkout@v2         
      - name: Install Quasar/cli  
        run: npm install -g @quasar/cli
      - name: Install project
        run: npm install      
      - name: Build project         
        run: quasar build         
      - name: Publish project  
        uses: crazy-max/ghaction-github-pages@v2        
        with:
          target_branch: gh-pages
          build_dir: dist/spa
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          API_KEY: ${{ secrets.API_KEY }}
          AUTH_DOMAIN: ${{ secrets.AUTH_DOMAIN }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          STORAGE_BUCKET: ${{ secrets.STORAGE_BUCKET }}
          MESSAGING_SENDER_ID: ${{ secrets.MESSAGING_SENDER_ID }}
          APP_ID: ${{ secrets.APP_ID }}
          
      