name: Deploy
on:
  push:
    branches:
      - 'master'      
jobs: 
  deploy:
    name: Quasar Publish
    runs-on: ubuntu-20.04
    container: node:12.16.2
    steps:
      - uses: actions/checkout@v2         
      - name: Install Quasar/cli  
        run: npm install -g @quasar/cli
      - name: Install project
        run: npm install 
      - name: Create .env file
        run: touch .env  
      - name: API_KEY 
        run:  echo API_KEY=${{ secrets.API_KEY }} >> .env 
      - name: AUTH_DOMAIN   
        run: echo AUTH_DOMAIN=${{ secrets.AUTH_DOMAIN }} >> .env
      - name: DATABASE_URL  
        run: echo DATABASE_URL=${{ secrets.DATABASE_URL }} >> .env
      - name: PROJECT_ID  
        run: echo PROJECT_ID=${{ secrets.PROJECT_ID }} >> .env
      - name: STORAGE_BUCKET  
        run: echo STORAGE_BUCKET=${{ secrets.STORAGE_BUCKET }} >> .env    
      - name: MESSAGING_SENDER_ID  
        run: echo MESSAGING_SENDER_ID=${{ secrets.MESSAGING_SENDER_ID }} >> .env
      - name: APP_ID  
        run: echo APP_ID=${{ secrets.APP_ID }} >> .env  
      - name: Build project         
        run: quasar build         
      - name: Publish project  
        uses: crazy-max/ghaction-github-pages@v2        
        with:
          target_branch: gh-pages
          build_dir: dist/spa
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      