name: Deploy
on:
  push:
    branches:
      - 'master'      
jobs: 
  deploy:
    name: Quasar Publish
    runs-on: ubuntu-20.04
    container: node:12.16.2
    steps:
      - uses: actions/checkout@v2         
      - name: Install Quasar/cli  
        run: npm install -g @quasar/cli
      - name: Install project
        run: npm install 
      - name: Create .env file
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_API_KEY: ${{ secrets.API_KEY }}    
          envkey_AUTH_DOMAIN: ${{ secrets.AUTH_DOMAIN }}  
          envkey_DATABASE_URL: ${{ secrets.DATABASE_URL }} 
          envkey_PROJECT_ID : ${{ secrets.PROJECT_ID }}
          envkey_STORAGE_BUCKET : ${{ secrets.STORAGE_BUCKET }} 
          envkey_MESSAGING_SENDER_ID: ${{ secrets.MESSAGING_SENDER_ID }} 
          envkey_APP_ID: ${{ secrets.APP_ID }}
      - name: Build project         
        run: quasar build         
      - name: Publish project  
        uses: crazy-max/ghaction-github-pages@v2        
        with:
          target_branch: gh-pages
          build_dir: dist/spa
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      